name: qis_quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.4.2+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_gauges: ^27.1.51
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_gen:
  output: lib/utils/
  integrations:
    flutter_svg: true
